"""Added accentric factor for compounds

Revision ID: 06472e7f6232
Revises: 3363cd61d14e
Create Date: 2025-04-07 21:19:31.846852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06472e7f6232'
down_revision: Union[str, None] = '3363cd61d14e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound_table', sa.Column('accentric', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compound_table', 'accentric')
    # ### end Alembic commands ###
